CREATE TABLE TB_OCF_SESSION_INFO (
PARTITION_ID             INTEGER       NOT NULL,
SUBSCRIBER_ID            BIGINT        NOT NULL,
ID                       VARCHAR(128)  NOT NULL,
DEVICE_ID                BIGINT        NOT NULL,
DEVICE_IDENTIFIER_TYPE   INTEGER       NOT NULL,

DEVICE_IDENTIFIER        VARCHAR(128)  NOT NULL,
LAST_CC_REQ_NUM          BIGINT        NOT NULL,
LAST_RESULT_CODE         BIGINT        NOT NULL,
SERVICE_TYPE             INTEGER       NOT NULL,
MISISDN                  VARCHAR(30),

OCF_HOST                 VARCHAR(30),
NE_LINK_HOST             VARCHAR(100),
NE_LINK_REALM            VARCHAR(80),
NE_RO_HOST               VARCHAR(100),
NE_RO_REALM              VARCHAR(80),

SESSION_STARTTIME        TIMESTAMP,
CAN_TYPE                 INTEGER,

RAN_TYPE                 INTEGER,
SN_TYPE                  INTEGER,
UE_TYPE                  BIGINT,
ACCESS_NETWORK_TYPE      INTEGER,
ROAM_TYPE                VARCHAR(6),

CALL_DIR                 VARCHAR(6),
CALL_CONN_TIME           TIMESTAMP,
CHARGED_NBR              VARCHAR(15),
CALLING_NBR              VARCHAR(15),
CALLED_NBR               VARCHAR(15),

CALLED_COUNTRY           VARCHAR(15),
CALLED_OPR               VARCHAR(15),
CALLED_PLMN              VARCHAR(15),
CALLED_ZONE1             INTEGER,
CALLED_ZONE2             INTEGER,

CALL_DISTANCE_TYPE       VARCHAR(6),
CALLED_PARTY_NET_TYPE    VARCHAR(6),
HOME_COUNTRY             VARCHAR(15),
HOME_OPR                 VARCHAR(15),
HOME_PLMN                VARCHAR(15),

HOME_ZONE1               BIGINT,
HOME_ZONE2               BIGINT,
VISITED_COUNTRY          VARCHAR(15),
VISITED_OPERATOR         VARCHAR(15),
VISITED_PLMN             VARCHAR(15),

VISITED_ZONE1            INTEGER,
VISITED_ZONE2            INTEGER,
VISITED_NE1              INTEGER,
VISITED_NE2              INTEGER,
APN                      VARCHAR(15),

SHAR                     VARCHAR(15),
IMS_ACCESS_NET_CLASS     INTEGER,
IMS_ACCESS_NET_TYPE      INTEGER,
PREMIUM_NBR_CLASS        INTEGER,
DIALED_NBR               VARCHAR(15),

SERVICE_PARAMETERS       VARCHAR(10240),
RATING_GROUP_INFOS       VARCHAR(10240),
QUOTA_INFOS              VARCHAR(10240),
COUNTER_INFOS            VARCHAR(10240),
ACCOUNTITEM_INFOS        VARCHAR(10240),

BALANCE_INFOS            VARCHAR(10240),
STATUS                   INTEGER,
EXTENDED_ATTRIBUTES      VARCHAR(10240),
RAR_COUNTER              INTEGER,
CREATE_TIME              TIMESTAMP,

LAST_UPDATE_TIME         TIMESTAMP,
CONSTRAINT PK_TB_OCF_SESSION_INFO PRIMARY KEY (PARTITION_ID, SUBSCRIBER_ID, ID)
);

CREATE INDEX IDX_TB_OCF_SESSION_INFO_ID on TB_OCF_SESSION_INFO (PARTITION_ID, ID);
CREATE INDEX IDX_TB_OCF_SESSION_INFO_DEVICE_IDENTIFIER on TB_OCF_SESSION_INFO (PARTITION_ID, DEVICE_IDENTIFIER_TYPE, DEVICE_IDENTIFIER);
CREATE INDEX IDX_TB_OCF_SESSION_INFO_RAR_CONDITION on TB_OCF_SESSION_INFO (PARTITION_ID, LAST_UPDATE_TIME, RAR_COUNTER, STATUS);

PARTITION TABLE TB_OCF_SESSION_INFO ON COLUMN PARTITION_ID;
DR TABLE TB_OCF_SESSION_INFO;

CREATE TABLE TB_OCF_RETRANSMIT_RECORD (
    PARTITION_ID             INTEGER       NOT NULL,
    ORIGIN_HOST              VARCHAR(100)   NOT NULL,
    ID                       BIGINT        NOT NULL,
    SUBSCRIBER_ID            BIGINT        NOT NULL,
    SESSION_ID               VARCHAR(128)  NOT NULL,
    CC_REQ_NUM               BIGINT        NOT NULL,
    RO_CCA                   VARBINARY(10240),
    SPR_SESSION_DATA         VARCHAR(10240) NOT NULL,
    CREATE_TIME              TIMESTAMP,
	CONSTRAINT PK_TB_OCF_RETRANSMIT_RECORD PRIMARY KEY (PARTITION_ID, ORIGIN_HOST, ID)

);
CREATE INDEX TB_OCF_RETRANSMIT_RECORD_IDX ON TB_OCF_RETRANSMIT_RECORD (PARTITION_ID, CREATE_TIME);

PARTITION TABLE TB_OCF_RETRANSMIT_RECORD ON COLUMN PARTITION_ID;
DR TABLE TB_OCF_RETRANSMIT_RECORD;

CREATE TABLE TB_OCF_SESSION_PARAMS_ULTD (
    PARTITION_ID             INTEGER       NOT NULL,
    SESSION_ID               VARCHAR(128)  NOT NULL,
    CATEGORY                 VARCHAR(32)   NOT NULL,
    PARAMETER                VARCHAR(10240) NOT NULL,
    CREATE_TIME              TIMESTAMP,
    CONSTRAINT PK_TB_OCF_SESSION_PARAMS_ULTD PRIMARY KEY (PARTITION_ID, SESSION_ID, CATEGORY)
);

PARTITION TABLE TB_OCF_SESSION_PARAMS_ULTD ON COLUMN PARTITION_ID;
DR TABLE TB_OCF_SESSION_PARAMS_ULTD;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFCreateSessionWithParamUltdProc;
PARTITION PROCEDURE OCFCreateSessionWithParamUltdProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFCreateSessionWithParamUltdProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFCreateSessionWithParamUltdProc ON TABLE TB_OCF_SESSION_PARAMS_ULTD   COLUMN PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadSessionProcWithParamUltd;
PARTITION PROCEDURE OCFLoadSessionProcWithParamUltd ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID;
PARTITION PROCEDURE OCFLoadSessionProcWithParamUltd ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN  PARTITION_ID;
PARTITION PROCEDURE OCFLoadSessionProcWithParamUltd ON TABLE TB_OCF_SESSION_PARAMS_ULTD COLUMN  PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFUpdateSessionProcWithParamUltd;
PARTITION PROCEDURE OCFUpdateSessionProcWithParamUltd ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFUpdateSessionProcWithParamUltd ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFUpdateSessionProcWithParamUltd ON TABLE TB_OCF_SESSION_PARAMS_ULTD COLUMN  PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFDeleteSessionWithParamUltdProc;
PARTITION PROCEDURE OCFDeleteSessionWithParamUltdProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFDeleteSessionWithParamUltdProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFDeleteSessionWithParamUltdProc ON TABLE TB_OCF_SESSION_PARAMS_ULTD COLUMN  PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFCreateSessionProc;
PARTITION PROCEDURE OCFCreateSessionProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFCreateSessionProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadSessionProc;
PARTITION PROCEDURE OCFLoadSessionProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadSessionProcWithRR;
PARTITION PROCEDURE OCFLoadSessionProcWithRR ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID;
PARTITION PROCEDURE OCFLoadSessionProcWithRR ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN  PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFUpdateSessionProc;
PARTITION PROCEDURE OCFUpdateSessionProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFUpdateSessionProc ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN  PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFDeleteSessionProc;
PARTITION PROCEDURE OCFDeleteSessionProc ON TABLE TB_OCF_SESSION_INFO  COLUMN PARTITION_ID PARAMETER 1;
PARTITION PROCEDURE OCFDeleteSessionProc ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN  PARTITION_ID PARAMETER 1;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadRARSessionProc;
PARTITION PROCEDURE OCFLoadRARSessionProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadRARSessionBySubscriberIdProc;
PARTITION PROCEDURE OCFLoadRARSessionBySubscriberIdProc ON TABLE TB_OCF_SESSION_INFO COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFUpdateRARCounterProc;
PARTITION PROCEDURE OCFUpdateRARCounterProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFLoadRetransmitRecordProc;
PARTITION PROCEDURE OCFLoadRetransmitRecordProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFDeleteRetransmitRecordProc;
PARTITION PROCEDURE OCFDeleteRetransmitRecordProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFDeleteRetransmitRecordByKeyProc;
PARTITION PROCEDURE OCFDeleteRetransmitRecordByKeyProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFInsertRetransmitRecordProc;
PARTITION PROCEDURE OCFInsertRetransmitRecordProc ON TABLE TB_OCF_RETRANSMIT_RECORD   COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFQuerySessionByDeviceIdentifierProc;
PARTITION PROCEDURE OCFQuerySessionByDeviceIdentifierProc ON TABLE TB_OCF_SESSION_INFO COLUMN PARTITION_ID;
PARTITION PROCEDURE OCFQuerySessionByDeviceIdentifierProc ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFQuerySessionBySessionIdProc;
PARTITION PROCEDURE OCFQuerySessionBySessionIdProc ON TABLE TB_OCF_SESSION_INFO COLUMN PARTITION_ID;
PARTITION PROCEDURE OCFQuerySessionBySessionIdProc ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN PARTITION_ID;

CREATE PROCEDURE FROM CLASS  com.hpe.snap.rtc.vdb.procedures.ocs.session.OCFQuerySessionBySubscriberIdProc;
PARTITION PROCEDURE OCFQuerySessionBySubscriberIdProc ON TABLE TB_OCF_SESSION_INFO COLUMN PARTITION_ID;
PARTITION PROCEDURE OCFQuerySessionBySubscriberIdProc ON TABLE TB_OCF_RETRANSMIT_RECORD COLUMN PARTITION_ID;
