Deployment:
  - VOLTDB_INSTANCE_NAME: spr_db
    DATABASE_NAME: spr_db
    VOLTDB_NODE_LIST:
      - external_interface: 15.116.78.152
        internal_interface: 15.116.78.152
        httpd_interface: 15.116.78.152
        replication_interface: 15.116.78.152
        admin_interface: 15.116.78.152
    VOLTDB_STORE_PATH: /var/opt/SIU_snap/voltdb/dbs/session
    VOLTDB_CLIENT_PORT: 11212
    VOLTDB_ADMIN_PORT: 11213
    VOLTDB_HTTP_PORT: 11214
    VOLTDB_INTERNAL_PORT: 11215
    VOLTDB_ZOOKEEPER_PORT: 11216
    VOLTDB_REPLICATION_PORT: 11217
    VOLTDB_USER_NAME: spr_user
    VOLTDB_USER_PASSWORD: %ENCRYPTED%A2B119A01D1E2A0561C22754DF40D2D3
    VOLTDB_ADMIN_USERNAME: vdbadmin
    VOLTDB_ADMIN_PASSWORD: %ENCRYPTED%5AEE3B799827803F61C22754DF40D2D3
    VOLTDB_START_PORT: 11215
    VOLTDB_WORK_MODEL: ACTIVE
    VDB_SSH_USER: snap
    VDB_HOST_NODE: 15.116.78.152
    VOLTDB_PLACEMENT_GROUPS:
     - external_interface: 15.116.78.152
       placement_group: China.SH.SiteA_server1






