insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AED', 784, 2, 'United Arab Emirates dirham', ' United Arab Emirates', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AFN', 971, 2, 'Afghan afghani', ' Afghanistan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ALL', 8, 2, 'Albanian lek', ' Albania', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AMD', 51, 2, 'Armenian dram', ' Armenia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ANG', 532, 2, 'Netherlands Antillean guilder', ' Cura?ao, Sint Maarten', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AOA', 973, 2, 'Angolan kwanza', ' Angola', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ARS', 32, 2, 'Argentine peso', ' Argentina', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AUD', 36, 2, 'Australian dollar', ' Australia, Australian Antarctic Territory, Christmas Island, Cocos (Keeling) Islands, Heard and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AWG', 533, 2, 'Aruban florin', ' Aruba', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('AZN', 944, 2, 'Azerbaijani manat', ' Azerbaijan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BAM', 977, 2, 'Bosnia and Herzegovina convertible mark', ' Bosnia and Herzegovina', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BBD', 52, 2, 'Barbados dollar', ' Barbados', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BDT', 50, 2, 'Bangladeshi taka', ' Bangladesh', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BGN', 975, 2, 'Bulgarian lev', ' Bulgaria', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BHD', 48, 3, 'Bahraini dinar', ' Bahrain', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BIF', 108, 0, 'Burundian franc', ' Burundi', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BMD', 60, 2, 'Bermudian dollar (customarily known as Bermuda dollar)', ' Bermuda', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BND', 96, 2, 'Brunei dollar', ' Brunei, Singapore', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BOB', 68, 2, 'Boliviano', ' Bolivia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BOV', 984, 2, 'Bolivian Mvdol (funds code)', ' Bolivia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BRL', 986, 2, 'Brazilian real', ' Brazil', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BSD', 44, 2, 'Bahamian dollar', ' Bahamas', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BTN', 64, 2, 'Bhutanese ngultrum', ' Bhutan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BWP', 72, 2, 'Botswana pula', ' Botswana', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BYR', 974, 0, 'Belarusian ruble', ' Belarus', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('BZD', 84, 2, 'Belize dollar', ' Belize', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CAD', 124, 2, 'Canadian dollar', ' Canada', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CDF', 976, 2, 'Congolese franc', ' Democratic Republic of Congo', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CHE', 947, 2, 'WIR Euro (complementary currency)', ' Switzerland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CHF', 756, 2, 'Swiss franc', ' Switzerland, Liechtenstein', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CHW', 948, 2, 'WIR Franc (complementary currency)', ' Switzerland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CLF', 990, 0, 'Unidad de Fomento (funds code)', ' Chile', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CLP', 152, 0, 'Chilean peso', ' Chile', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CNY', 156, 2, 'Chinese yuan', ' China', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('COP', 170, 2, 'Colombian peso', ' Colombia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('COU', 970, 2, 'Unidad de Valor Real', ' Colombia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CRC', 188, 2, 'Costa Rican colon', ' Costa Rica', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CUC', 931, 2, 'Cuban convertible peso', ' Cuba', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CUP', 192, 2, 'Cuban peso', ' Cuba', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CVE', 132, 0, 'Cape Verde escudo', ' Cape Verde', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('CZK', 203, 2, 'Czech koruna', ' Czech Republic', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('DJF', 262, 0, 'Djiboutian franc', ' Djibouti', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('DKK', 208, 2, 'Danish krone', ' Denmark, Faroe Islands, Greenland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('DOP', 214, 2, 'Dominican peso', ' Dominican Republic', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('DZD', 12, 2, 'Algerian dinar', ' Algeria', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('EGP', 818, 2, 'Egyptian pound', ' Egypt', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ERN', 232, 2, 'Eritrean nakfa', ' Eritrea', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ETB', 230, 2, 'Ethiopian birr', ' Ethiopia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('EUR', 978, 2, 'Euro', ' Andorra, Austria, Belgium, Cyprus, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Kosovo, Luxembourg, Malta, Monaco, Montenegro, Netherlands, Portugal, San Marino, Slovakia, Slovenia, Spain, Vatican City; see eurozone', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('FJD', 242, 2, 'Fiji dollar', ' Fiji', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('FKP', 238, 2, 'Falkland Islands pound', ' Falkland Islands', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GBP', 826, 2, 'Pound sterling', ' United Kingdom, British Crown dependencies (the Isle of Man and the Channel Islands), certain British Overseas Territories ( South Georgia and the South Sandwich Islands, British Antarctic Territory and British Indian Ocean Territory)', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GEL', 981, 2, 'Georgian lari', ' Georgia (country)', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GHS', 936, 2, 'Ghanaian cedi', ' Ghana', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GIP', 292, 2, 'Gibraltar pound', ' Gibraltar', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GMD', 270, 2, 'Gambian dalasi', ' Gambia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GNF', 324, 0, 'Guinean franc', ' Guinea', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GTQ', 320, 2, 'Guatemalan quetzal', ' Guatemala', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('GYD', 328, 2, 'Guyanese dollar', ' Guyana', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('HKD', 344, 2, 'Hong Kong dollar', ' Hong Kong, Macao', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('HNL', 340, 2, 'Honduran lempira', ' Honduras', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('HRK', 191, 2, 'Croatian kuna', ' Croatia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('HTG', 332, 2, 'Haitian gourde', ' Haiti', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('HUF', 348, 2, 'Hungarian forint', ' Hungary', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('IDR', 360, 2, 'Indonesian rupiah', ' Indonesia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ILS', 376, 2, 'Israeli new shekel', ' Israel, Palestinian territories[7]', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('INR', 356, 2, 'Indian rupee', ' India', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('IQD', 368, 3, 'Iraqi dinar', ' Iraq', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('IRR', 364, 0, 'Iranian rial', ' Iran', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ISK', 352, 0, 'Icelandic króna', ' Iceland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('JMD', 388, 2, 'Jamaican dollar', ' Jamaica', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('JOD', 400, 3, 'Jordanian dinar', ' Jordan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('JPY', 392, 0, 'Japanese yen', ' Japan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KES', 404, 2, 'Kenyan shilling', ' Kenya', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KGS', 417, 2, 'Kyrgyzstani som', ' Kyrgyzstan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KHR', 116, 2, 'Cambodian riel', ' Cambodia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KMF', 174, 0, 'Comoro franc', ' Comoros', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KPW', 408, 0, 'North Korean won', ' North Korea', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KRW', 410, 0, 'South Korean won', ' South Korea', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KWD', 414, 3, 'Kuwaiti dinar', ' Kuwait', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KYD', 136, 2, 'Cayman Islands dollar', ' Cayman Islands', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('KZT', 398, 2, 'Kazakhstani tenge', ' Kazakhstan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LAK', 418, 0, 'Lao kip', ' Laos', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LBP', 422, 0, 'Lebanese pound', ' Lebanon', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LKR', 144, 2, 'Sri Lankan rupee', ' Sri Lanka', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LRD', 430, 2, 'Liberian dollar', ' Liberia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LSL', 426, 2, 'Lesotho loti', ' Lesotho', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LTL', 440, 2, 'Lithuanian litas', ' Lithuania', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LVL', 428, 2, 'Latvian lats', ' Latvia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('LYD', 434, 3, 'Libyan dinar', ' Libya', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MAD', 504, 2, 'Moroccan dirham', ' Morocco', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MDL', 498, 2, 'Moldovan leu', ' Moldova (except Transnistria)', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MGA', 969, 0, 'Malagasy ariary', ' Madagascar', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MKD', 807, 0, 'Macedonian denar', ' Macedonia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MMK', 104, 0, 'Myanma kyat', ' Myanmar', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MNT', 496, 2, 'Mongolian tugrik', ' Mongolia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MOP', 446, 2, 'Macanese pataca', ' Macao', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MRO', 478, 0, 'Mauritanian ouguiya', ' Mauritania', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MUR', 480, 2, 'Mauritian rupee', ' Mauritius', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MVR', 462, 2, 'Maldivian rufiyaa', ' Maldives', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MWK', 454, 2, 'Malawian kwacha', ' Malawi', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MXN', 484, 2, 'Mexican peso', ' Mexico', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MXV', 979, 2, 'Mexican Unidad de Inversion (UDI) (funds code)', ' Mexico', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MYR', 458, 2, 'Malaysian ringgit', ' Malaysia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('MZN', 943, 2, 'Mozambican metical', ' Mozambique', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NAD', 516, 2, 'Namibian dollar', ' Namibia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NGN', 566, 2, 'Nigerian naira', ' Nigeria', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NIO', 558, 2, 'Nicaraguan córdoba', ' Nicaragua', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NOK', 578, 2, 'Norwegian krone', ' Norway, Svalbard, Jan Mayen, Bouvet Island, Queen Maud Land, Peter I Island', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NPR', 524, 2, 'Nepalese rupee', ' Nepal', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('NZD', 554, 2, 'New Zealand dollar', ' Cook Islands, New Zealand, Niue, Pitcairn, Tokelau, Ross Dependency', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('OMR', 512, 3, 'Omani rial', ' Oman', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PAB', 590, 2, 'Panamanian balboa', ' Panama', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PEN', 604, 2, 'Peruvian nuevo sol', ' Peru', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PGK', 598, 2, 'Papua New Guinean kina', ' Papua New Guinea', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PHP', 608, 2, 'Philippine peso', ' Philippines', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PKR', 586, 2, 'Pakistani rupee', ' Pakistan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PLN', 985, 2, 'Polish z?oty', ' Poland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('PYG', 600, 0, 'Paraguayan guaraní', ' Paraguay', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('QAR', 634, 2, 'Qatari riyal', ' Qatar', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('RON', 946, 2, 'Romanian new leu', ' Romania', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('RSD', 941, 2, 'Serbian dinar', ' Serbia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('RUB', 643, 2, 'Russian rouble', ' Russia, Abkhazia, South Ossetia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('RWF', 646, 0, 'Rwandan franc', ' Rwanda', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SAR', 682, 2, 'Saudi riyal', ' Saudi Arabia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SBD', 90, 2, 'Solomon Islands dollar', ' Solomon Islands', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SCR', 690, 2, 'Seychelles rupee', ' Seychelles', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SDG', 938, 2, 'Sudanese pound', ' Sudan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SEK', 752, 2, 'Swedish krona/kronor', ' Sweden', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SGD', 702, 2, 'Singapore dollar', ' Singapore, Brunei', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SHP', 654, 2, 'Saint Helena pound', ' Saint Helena', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SLL', 694, 0, 'Sierra Leonean leone', ' Sierra Leone', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SOS', 706, 2, 'Somali shilling', ' Somalia (except Somaliland)', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SRD', 968, 2, 'Surinamese dollar', ' Suriname', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SSP', 728, 2, 'South Sudanese pound', ' South Sudan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('STD', 678, 0, 'S?o Tomé and Príncipe dobra', ' S?o Tomé and Príncipe', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SYP', 760, 2, 'Syrian pound', ' Syria', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('SZL', 748, 2, 'Swazi lilangeni', ' Swaziland', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('THB', 764, 2, 'Thai baht', ' Thailand', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TJS', 972, 2, 'Tajikistani somoni', ' Tajikistan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TMT', 934, 2, 'Turkmenistani manat', ' Turkmenistan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TND', 788, 3, 'Tunisian dinar', ' Tunisia', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TOP', 776, 2, 'Tongan pa?anga', ' Tonga', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TRY', 949, 2, 'Turkish lira', ' Turkey', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TTD', 780, 2, 'Trinidad and Tobago dollar', ' Trinidad and Tobago', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TWD', 901, 2, 'New Taiwan dollar', ' Taiwan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('TZS', 834, 2, 'Tanzanian shilling', ' Tanzania', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('UAH', 980, 2, 'Ukrainian hryvnia', ' Ukraine', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('UGX', 800, 2, 'Ugandan shilling', ' Uganda', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('USD', 840, 2, 'United States dollar', 'American Samoa, Barbados (as well as Barbados Dollar), Bermuda (as well as Bermudian Dollar), British Indian Ocean Territory, British Virgin Islands, Caribbean Netherlands, Ecuador, El Salvador, Guam, Haiti, Marshall Islands', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('USN', 997, 2, 'United States dollar (next day) (funds code)', ' United States', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('USS', 998, 2, 'United States dollar (same day) (funds code)...', ' United States', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('UYI', 940, 0, 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)', ' Uruguay', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('UYU', 858, 2, 'Uruguayan peso', ' Uruguay', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('UZS', 860, 2, 'Uzbekistan som', ' Uzbekistan', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('VEF', 937, 2, 'Venezuelan bolívar fuerte', ' Venezuela', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('VND', 704, 0, 'Vietnamese dong', ' Vietnam', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('VUV', 548, 0, 'Vanuatu vatu', ' Vanuatu', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('WST', 882, 2, 'Samoan tala', ' Samoa', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XAF', 950, 0, 'CFA franc BEAC', ' Cameroon, Central African Republic, Republic of the Congo, Chad, Equatorial Guinea, Gabon', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XAG', 961, 0, 'Silver (one troy ounce)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XAU', 959, 0, 'Gold (one troy ounce)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XBA', 955, 0, 'European Composite Unit (EURCO) (bond market unit)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XBB', 956, 0, 'European Monetary Unit (E0M0U0-6) (bond market unit)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XBC', 957, 0, 'European Unit of Account 9 (E0U0A0-9) (bond market unit)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XBD', 958, 0, 'European Unit of Account 17 (E0U0A0-17) (bond market unit)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XCD', 951, 2, 'East Caribbean dollar', ' Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XDR', 960, 0, 'Special drawing rights', 'International Monetary Fund', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XFU', 0, 0, 'UIC franc (special settlement currency)', 'International Union of Railways', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XOF', 952, 0, 'CFA franc BCEAO', ' Benin, Burkina Faso, C?te d''Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XPD', 964, 0, 'Palladium (one troy ounce)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XPF', 953, 0, 'CFP franc', ' French Polynesia, New Caledonia, Wallis and Futuna', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XPT', 962, 0, 'Platinum (one troy ounce)', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XTS', 963, 0, 'Code reserved for testing purposes', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('XXX', 999, 0, 'No currency', null, 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('YER', 886, 2, 'Yemeni rial', ' Yemen', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ZAR', 710, 2, 'South African rand', ' South Africa', 'A', 0, 0);
insert into CURRENCY_CODES (ID, NUM_CODE, FRACTIONAL_DIGITS, FULL_NAME, LOCATIONS, STATE_LIFECYCLE, CREATE_TIME, LAST_UPDATE_TIME)
values ('ZMW', 967, 2, 'Zambian kwacha', ' Zambia', 'A', 0, 0);
